version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306" 

  api:
    build: .
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - db
    links: 
      - db  
    environment:
      DB_USER: root
      DB_NAME: myapp
      DB_PASSWORD: password  
      DB_HOST: db
      